name: commandlogger
version: ${project.version}
main: com.creativecommmons.commandlogger.commandlogger
api-version: 1.16
author: creativecommmons
website: https://github.com/creativecommmons/commandlogger